[package]
name = "rana"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["Francisco Calderón <fjcalderon@gmail.com>"]

[dependencies]
bitcoin_hashes = "0.11.0"
secp256k1 = { version = "0.24.0", features = ["rand-std"] }
num_cpus = "1.1"
