[package]
name = "rana"
version = "0.1.0"
edition = "2021"
authors = ["Francisco Calderón <fjcalderon@gmail.com>"]

[dependencies]
bitcoin_hashes = "0.11.0"
env_logger = "0.9.1"
log = "0.4.17"
nostr = { path = "nostr" }
secp256k1 = "0.24.0"
