[package]
name = "rana"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Francisco Calderón <fjcalderon@gmail.com>"]

[dependencies]
bitcoin_hashes = "0.11.0"
nostr = { git = "https://github.com/grunch/nostr-rs.git", commit = "b3cb95620a3dab5850690e9e77d54b7647f1bfdb" }
secp256k1 = "0.24.0"
